{
 "title": "Instance Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "role", "query": "label_values(role)" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Systemd Units",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_systemd_units{state = \"activating\"}",
     "legendFormat": "{{instance}} activating"
    },
    {
     "expr": "node_systemd_units{state = \"deactivating\"}",
     "legendFormat": "{{instance}} deactivating"
    },
    {
     "expr": "node_systemd_units{state = \"failed\"}",
     "legendFormat": "{{instance}} failed"
    },
    {
     "expr": "node_systemd_units{state = \"active\"}",
     "legendFormat": "{{instance}} active"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "100% means every CPU was fully loaded.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",role=~\"^($role)$\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{mode=\"idle\",role=~\"^($role)$\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes{role=~\"^($role)$\"}/node_memory_MemTotal_bytes{role=~\"^($role)$\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_context_switches_total{role=~\"^($role)$\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "irate(node_context_switches{role=~\"^($role)$\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{role=~\"^($role)$\",mode=\"iowait\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg by (instance) (irate(node_cpu{role=~\"^($role)$\",mode=\"iowait\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_free_bytes{mountpoint=\"/\",role=~\"^($role)$\"} / node_filesystem_size_bytes{mountpoint=\"/\",role=~\"^($role)$\"} )",
     "legendFormat": "{{instance}} Disk Space Usage"
    },
    {
     "expr": "1 - (node_filesystem_files_free{mountpoint=\"/\",role=~\"^($role)$\"} / node_filesystem_files{mountpoint=\"/\",role=~\"^($role)$\"})",
     "legendFormat": "{{instance}} Inode Usage"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{role=~\"^($role)$\"}[5m]) * 8)",
     "legendFormat": "{{instance}} RX"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{role=~\"^($role)$\"}[5m]) * 8)",
     "legendFormat": "{{instance}} TX"
    }
   ]
  },
  {
   "title": "1m load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_load1{role=~\"^($role)$\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Consecutive Build Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hydra_machine_consecutive_failures * hydra_machine_enabled > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Build Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hydra_machine_current_jobs", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Step Build Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hydra_machine_step_build_time_total / hydra_machine_steps_done_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Builds Completed In The Last 30 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hydra_machine_steps_done_total[30m])",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}