{
 "title": "Exchange Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bittrex",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "bittrex_active" }
   ]
  },
  {
   "title": "Binance",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "binance_deposits{job=\"exchange-monitor\"} + binance_withdraws{job=\"exchange-monitor\"}"
    }
   ]
  },
  {
   "title": "Bitthumb",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "bithumb_active" }
   ]
  },
  {
   "title": "HitBTC",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hitbtc_deposits{job=\"exchange-monitor\"} + hitbtc_withdraws{job=\"exchange-monitor\"}"
    }
   ]
  },
  {
   "title": "Coinex",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "coinex_deposits{job=\"exchange-monitor\"} + coinex_withdraws{job=\"exchange-monitor\"}"
    }
   ]
  },
  {
   "title": "Bitmax Active",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "bitmax_active" }
   ]
  },
  {
   "title": "Bittrex 4w Uptime %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(bittrex_active[4w:1m]) * 100 / (4 * 7 * 24 * 60)"
    }
   ]
  },
  {
   "title": "Binance 4w Uptime %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum_over_time((binance_deposits{job=\"exchange-monitor\"} + binance_withdraws{job=\"exchange-monitor\"} == bool 2)[4w:1m])) * 100 / (4 * 7 * 24 * 60)"
    }
   ]
  },
  {
   "title": "Bitthumb 4w Uptime %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(bithumb_active[4w:1m]) * 100 / (4 * 7 * 24 * 60)"
    }
   ]
  },
  {
   "title": "HitBTC 4w Uptime %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum_over_time((hitbtc_deposits{job=\"exchange-monitor\"} + hitbtc_withdraws{job=\"exchange-monitor\"} == bool 2)[4w:1m])) * 100 / (4 * 7 * 24 * 60)"
    }
   ]
  },
  {
   "title": "Coinex 4w Uptime %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum_over_time((coinex_deposits{job=\"exchange-monitor\"} + coinex_withdraws{job=\"exchange-monitor\"} == bool 2)[4w:1m])) * 100 / (4 * 7 * 24 * 60)"
    }
   ]
  },
  {
   "title": "Bitmax 4w Uptime %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(bitmax_active[4w:1m]) * 100 / (4 * 7 * 24 * 60)"
    }
   ]
  },
  {
   "title": "Binance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Binance Metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "binance_deposits" },
      { "expr": "binance_withdraws" },
      { "expr": "min(binance_withdraws)" },
      { "expr": "max(binance_withdraws)" }
     ]
    }
   ]
  },
  {
   "title": "Bittrex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Online",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bittrex_active" }
     ]
    },
    {
     "title": "Withdraw Queue Depth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bittrex_withdraw_queue_depth" }
     ]
    }
   ]
  },
  {
   "title": "BitThumb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Online",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bithumb_active" }
     ]
    }
   ]
  },
  {
   "title": "Hit BTC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hit BTC",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "hitbtc_deposits" },
      { "expr": "hitbtc_withdraws" },
      { "expr": "min(hitbtc_withdraws)" },
      { "expr": "max(hitbtc_withdraws)" }
     ]
    }
   ]
  },
  {
   "title": "Coinex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coinex",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "coinex_deposits" },
      { "expr": "coinex_withdraws" },
      { "expr": "min(coinex_withdraws)" },
      { "expr": "max(coinex_withdraws)" }
     ]
    }
   ]
  },
  {
   "title": "Bitmax",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bitmax Status",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "bitmax_active" }
     ]
    }
   ]
  }
 ]
}