{
 "title": "Hydra Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "machine", "label": "machine", "query": "label_values(machine)" }
  ]
 },
 "panels": [
  {
   "title": "Steps Queued",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hydra_steps_queued" }
   ]
  },
  {
   "title": "Copying Inputs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hydra_steps_copying_to" }
   ]
  },
  {
   "title": "Running Steps",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hydra_steps_building" }
   ]
  },
  {
   "title": "Copying Results",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "hydra_steps_copying_from" }
   ]
  },
  {
   "title": "Runnable Jobs per Machine Type",
   "type": "graph",
   "description": "A build step is runnable if all of its dependencies have been built before. This graph does not include runnable steps which are currently running.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hydra_machine_type_runnable", "legendFormat": "{{machineType}}" }
   ]
  },
  {
   "title": "Running Jobs By Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "hydra_machine_type_running ", "legendFormat": "{{machineType}}" }
   ]
  },
  {
   "title": "Step Build Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hydra_machine_step_build_time_total / hydra_machine_steps_done_total",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Builds Completed In The Last 30 Minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hydra_machine_steps_done_total[30m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Total Running Jobs by Machine",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hydra_machine_current_jobs", "legendFormat": "{{host}}" }
   ]
  }
 ]
}