{
 "title": "Hydra",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Pending Builds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hydra Pending Builds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hydra_queue_builds_unfinished", "legendFormat": "{{alias}}" }
   ]
  },
  { "title": "Notification Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Pending Notifications",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hydra_queue_notification_pending",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Estimated Hydra Notify Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hydra_queue_notification_pending * hydra_queue_notification_time_avg_ms",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Load Avg", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Hydra Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=\"hydra.iohk-infra\"}",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "node_load5{alias=\"hydra.iohk-infra\"}",
     "legendFormat": "{{alias}}"
    },
    {
     "expr": "node_load15{alias=\"hydra.iohk-infra\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Http", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Nginx HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total{code=\"5xx\"}[5m]) > 0",
     "legendFormat": "Code 5xx"
    }
   ]
  },
  {
   "title": "Hydra CPU and RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true
  },
  {
   "title": "Hydra CPU Basic",
   "type": "graph",
   "description": "Hydra Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=\"hydra.iohk-infra:9100\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"hydra.iohk-infra:9100\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=\"hydra.iohk-infra:9100\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=\"hydra.iohk-infra:9100\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=\"hydra.iohk-infra:9100\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"hydra.iohk-infra:9100\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Hydra Memory Basic",
   "type": "graph",
   "description": "Hydra Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"hydra.iohk-infra:9100\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"hydra.iohk-infra:9100\"} - node_memory_MemFree_bytes{instance=\"hydra.iohk-infra:9100\"} - (node_memory_Cached_bytes{instance=\"hydra.iohk-infra:9100\"} + node_memory_Buffers_bytes{instance=\"hydra.iohk-infra:9100\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"hydra.iohk-infra:9100\"} + node_memory_Buffers_bytes{instance=\"hydra.iohk-infra:9100\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"hydra.iohk-infra:9100\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"hydra.iohk-infra:9100\"} - node_memory_SwapFree_bytes{instance=\"hydra.iohk-infra:9100\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Supporting CI Server Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true
  },
  {
   "title": "Packet Hydra Build Slaves, 1 min Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=~\"packet-hydra-slave-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packet Mantis Hydra Build Slaves, 1 min Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=~\"mantis-slave-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packet Buildkite Servers, 1 min Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=~\"packet-buildkite-.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mac Related CI Servers, 1 min Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=~\"sarov.*\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_load1{job=~\"mac-mini-.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Miscellaneous CI Related Servers, 1 min Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{alias=~\"bors.*|cardano-deployer.*|log-classifier.*|monitoring.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Supporting CI Server CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true
  },
  {
   "title": "Packet Hydra Build Slaves, 1 min avg CPU % Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=~\"packet-hydra-slave-.*\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packet Mantis Hydra Build Slaves, 1 min avg CPU % Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=~\"mantis-slave-.*\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packet Buildkite Servers, 1 min avg CPU % Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=~\"packet-buildkite-.*\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mac Related CI Servers, 1 min avg CPU % Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(job) (irate(node_cpu_seconds_total{mode=\"idle\",job=~\"sarov.*\"}[1m])) * 100)",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "100 - (avg by(job) (irate(node_cpu_seconds_total{mode=\"idle\",job=~\"mac-mini.*\"}[1m])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Miscellaneous CI Related Servers, 1 min avg CPU % Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=~\"bors.*|cardano-deployer.*|log-classifier.*|monitoring.*\"}[1m])) * 100)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Supporting CI Server Free RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true
  },
  {
   "title": "Packet Hydra Build Slaves, Free RAM (GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=~\"packet-hydra-slave-.*\"}/1024/1024/1024",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packet Mantis Hydra Build Slaves, Free RAM (GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=~\"mantis-slave-.*\"}/1024/1024/1024",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Packet Buildkite Servers, Free RAM (GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=~\"packet-buildkite-.*\"}/1024/1024/1024",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mac Related CI Servers, Free RAM (GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"sarov-.*\"}/1024/1024/1024",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_memory_free_bytes{job=~\"sarov-.*\"}/1024/1024/1024",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=~\"mac-mini-.*\"}/1024/1024/1024",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "node_memory_free_bytes{job=~\"mac-mini-.*\"}/1024/1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Miscellaneous CI Related Servers, Free RAM (GiB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{alias=~\"bors.*|cardano-deployer.*|log-classifier.*|monitoring.*\"}/1024/1024/1024",
     "legendFormat": "{{alias}}"
    }
   ]
  }
 ]
}