{
 "title": "Nginx Basic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_exporter_build_info, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_exporter_build_info{job=~\"$job\"}, instance)"
   },
   {
    "name": "nginx_host",
    "label": "Nginx host:",
    "query": "label_values(nginx_vts_server_requests_total{instance=~\"$node:9113\"},host)"
   }
  ]
 },
 "panels": [
  {
   "title": "2xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total{code=\"2xx\",instance=~\"$node:9113\",host=\"$nginx_host\"}[1m])"
    }
   ]
  },
  {
   "title": "4xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total{code=\"4xx\",instance=~\"$node:9113\",host=\"$nginx_host\"}[1m])"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total{code=\"5xx\",instance=~\"$node:9113\",host=\"$nginx_host\"}[1m])"
    }
   ]
  },
  {
   "title": "active connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_main_connections{status=\"active\",alias=\"$node\"}"
    }
   ]
  },
  {
   "title": "current epoch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_current_epoch{alias=\"c-a-1.mainnet\"}"
    }
   ]
  }
 ]
}