{
 "title": "Hydra Metrics Per Instance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Consecutive Build Failures",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hydra_machine_consecutive_failures{host=~\"^.*@($instance)$\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Build Jobs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hydra_machine_current_jobs{host=~\"^.*@($instance)$\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Step Build Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "hydra_machine_step_build_time_total{host=~\"^.*@($instance)$\"} / hydra_machine_steps_done_total{host=~\"^.*@($instance)$\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}